data=("MJK","BCA",5)
owniter=iter(data)
print("iteration data",owniter)
print("first iteration value",next(owniter))
print("second iteration value",next(owniter))
print("third iteration value",next(owniter))
